// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxMMXKsrqH-nj1NcQ9oYpzfb_GCBVA5EQ',
    appId: '1:865926350607:web:14b764de26e032fc69607a',
    messagingSenderId: '865926350607',
    projectId: 'qr-scanner-event-ticketing',
    authDomain: 'qr-scanner-event-ticketing.firebaseapp.com',
    storageBucket: 'qr-scanner-event-ticketing.firebasestorage.app',
    measurementId: 'G-H8KZTKKZER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClQVRKtW_qnJ5KcjB3cUN5L72BhVLVxyM',
    appId: '1:865926350607:android:e6eb495a73d96a6f69607a',
    messagingSenderId: '865926350607',
    projectId: 'qr-scanner-event-ticketing',
    storageBucket: 'qr-scanner-event-ticketing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5dZxYNkoceiN4rK3AA6eTuWf55vZlnmY',
    appId: '1:865926350607:ios:214a35962363c53a69607a',
    messagingSenderId: '865926350607',
    projectId: 'qr-scanner-event-ticketing',
    storageBucket: 'qr-scanner-event-ticketing.firebasestorage.app',
    iosBundleId: 'com.example.scannerEventLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5dZxYNkoceiN4rK3AA6eTuWf55vZlnmY',
    appId: '1:865926350607:ios:214a35962363c53a69607a',
    messagingSenderId: '865926350607',
    projectId: 'qr-scanner-event-ticketing',
    storageBucket: 'qr-scanner-event-ticketing.firebasestorage.app',
    iosBundleId: 'com.example.scannerEventLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxMMXKsrqH-nj1NcQ9oYpzfb_GCBVA5EQ',
    appId: '1:865926350607:web:55933b856c696d5c69607a',
    messagingSenderId: '865926350607',
    projectId: 'qr-scanner-event-ticketing',
    authDomain: 'qr-scanner-event-ticketing.firebaseapp.com',
    storageBucket: 'qr-scanner-event-ticketing.firebasestorage.app',
    measurementId: 'G-Z0HKS0SGQF',
  );
}
